# Generated by Django 4.1.6 on 2023-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('images', models.ImageField(default='images/default.svg', upload_to='images/')),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
