# Generated by Django 4.1.5 on 2023-02-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMe',
        ),
    ]
