# Generated by Django 4.1.5 on 2023-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_contactme'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactMeData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('cf_name', models.CharField(max_length=512)),
                ('cf_email', models.CharField(max_length=512)),
                ('cf_message', models.TextField()),
            ],
        ),
    ]
