# Generated by Django 4.1.5 on 2023-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactmedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmedata',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contactmedata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
