# Generated by Django 4.1.6 on 2023-02-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='passwd',
        ),
    ]
