# Generated by Django 4.1.6 on 2023-02-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faiapp', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
