# Generated by Django 4.1.6 on 2023-02-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('number', models.IntegerField()),
                ('emil', models.EmailField(max_length=254)),
            ],
        ),
    ]
