# Generated by Django 4.1.6 on 2023-02-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='emil',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='content',
        ),
    ]
