# Generated by Django 4.1.6 on 2023-02-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='MainModel',
        ),
    ]
