# Generated by Django 4.1.6 on 2023-02-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0005_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='about_content',
            new_name='service_content',
        ),
    ]
