# Generated by Django 4.1.6 on 2023-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0006_rename_about_content_services_service_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=102)),
                ('Phon', models.CharField(max_length=50)),
            ],
        ),
    ]
