# Generated by Django 4.1.6 on 2023-02-13 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_app', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Phon',
            new_name='Phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default="admin@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
