# Generated by Django 4.1.6 on 2023-02-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_form_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='telegram',
        ),
    ]
