# Generated by Django 4.1.5 on 2023-02-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='form',
        ),
    ]
