# Generated by Django 4.1.5 on 2023-02-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_comment_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
