# Generated by Django 4.1.6 on 2023-02-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteDashboard', '0002_rename_post_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='owner',
        ),
    ]
